args: !!python/object:argparse.Namespace
  accelerator: null
  accumulate_grad_batches: 1
  adam_epsilon: 1.0e-08
  amp_backend: native
  amp_level: O2
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  batch_size: 8
  benchmark: false
  bert_config_dir: "E:\\\u9879\u76EE\u8D44\u6599\\\u4E3B\u9898\u6316\u6398\u9879\u76EE\
    \\DataRepository\\bert_model"
  check_val_every_n_epoch: 1
  checkpoint_callback: true
  data_dir: ../../data/squad
  default_root_dir: null
  deterministic: false
  dice_alpha: 0.01
  dice_ohem: 0.0
  dice_smooth: 0.0001
  dice_square: false
  distributed_backend: null
  doc_stride: 128
  fast_dev_run: false
  final_div_factor: 10000.0
  flush_logs_every_n_steps: 100
  focal_alpha: null
  focal_gamma: 2
  gpus: null
  gradient_clip_algorithm: norm
  gradient_clip_val: 0.0
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  log_gpu_memory: null
  logger: true
  loss_type: bce
  lr: 2.0e-05
  lr_scheduler: onecycle
  max_answer_length: 30
  max_epochs: 1
  max_length: 128
  max_query_length: 64
  max_seq_length: 384
  max_steps: null
  max_time: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  n_best_size: 20
  num_nodes: 1
  num_processes: 1
  num_sanity_val_steps: -1
  optimizer: adamw
  output_dir: ./output_dir/
  overfit_batches: 0.0
  plugins: null
  precision: 32
  prepare_data_per_node: true
  pretrained_checkpoint: ''
  process_position: 0
  profiler: null
  progress_bar_refresh_rate: null
  reload_dataloaders_every_epoch: false
  replace_sampler_ddp: true
  resume_from_checkpoint: null
  stochastic_weight_avg: false
  sync_batchnorm: false
  terminate_on_nan: false
  tpu_cores: null
  track_grad_norm: -1
  truncated_bptt_steps: null
  val_check_interval: 1.0
  warmup_proportion: 0.1
  weight_decay: 0.01
  weights_save_path: null
  weights_summary: top
  with_negative: false
  workers: 0
